/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "example_constants.h"

namespace td { namespace test {

const exampleConstants g_example_constants;

exampleConstants::exampleConstants() {
}

}} // namespace

